{pkgs, ...}: {
  config.nvim.plugins = with pkgs.vimPlugins; [
    cmp-nvim-lsp
    coloresque
    conflict-marker-vim
    css3-syntax
    emmet-vim
    fidget-nvim
    gitsigns-nvim
    haml
    inlay-hints-nvim
    lazygit-nvim
    lualine-nvim
    luasnip
    neo-tree-nvim
    neosnippet
    neosnippet-snippets
    neovim-ayu
    nerdcommenter
    nvim-cmp
    nvim-config-local
    nvim-lspconfig
    nvim-treesitter-textobjects
    nvim-treesitter.withAllGrammars
    nvim-web-devicons
    python-mode
    rainbow
    syntastic
    tabular
    tagbar
    telescope-nvim
    telescope-recent-files
    trouble-nvim
    typescript-vim
    vaffle
    vim-closetag
    vim-commentary
    vim-fugitive
    vim-gist
    vim-highlightedyank
    vim-javascript
    vim-json
    vim-jsx-pretty
    vim-jsx-typescript
    vim-markdown
    vim-matchup
    vim-repeat
    vim-snippets
    vim-surround
    vim-toml
    webapi-vim
  ];
}
