{pkgs}:
with pkgs.vimPlugins; [
  coloresque
  conflict-marker-vim
  css3-syntax
  emmet-vim
  haml
  mason-lspconfig-nvim
  mason-nvim
  neo-tree-nvim
  neosnippet
  neosnippet-snippets
  nerdcommenter
  nvim-config-local
  nvim-lspconfig
  nvim-treesitter-textobjects
  nvim-treesitter.withAllGrammars
  python-mode
  rainbow
  syntastic
  tabular
  tagbar
  telescope-nvim
  telescope-recent-files
  typescript-vim
  vaffle
  vim-airline
  vim-airline-themes
  vim-closetag
  vim-commentary
  vim-fugitive
  vim-gist
  vim-highlightedyank
  vim-javascript
  vim-json
  vim-jsx-pretty
  vim-jsx-typescript
  vim-markdown
  vim-matchup
  vim-repeat
  vim-snippets
  vim-surround
  vim-toml
  webapi-vim
]
